In [111]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([0.5, 0.1, -0.2])
target = 0.6
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

print(hidden_layer_input)

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)
output = sigmoid(output_layer_in)

## Backwards pass
## TODO: Calculate output error
error = target - output

# TODO: Calculate error term for output layer
output_error_term = error * output * (1 - output)

print(output_error_term)

# TODO: Calculate error term for hidden layer
hidden_error_term = np.dot(output_error_term, weights_hidden_output) * \
                    hidden_layer_output * (1 - hidden_layer_output)

# TODO: Calculate change in weights for hidden layer to output layer
delta_w_h_o = learnrate * output_error_term * hidden_layer_output

# TODO: Calculate change in weights for input layer to hidden layer
delta_w_i_h = learnrate * hidden_error_term * x[:, None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)


[ 0.24 -0.46]
0.0287306695435
Change in weights for hidden layer to output layer:
[ 0.00804047  0.00555918]
Change in weights for input layer to hidden layer:
[[  1.77005547e-04  -5.11178506e-04]
 [  3.54011093e-05  -1.02235701e-04]
 [ -7.08022187e-05   2.04471402e-04]]


In [113]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.array([0.5, 0.1, -0.2])
y = 0.6
X = np.array([x]).T
Y = np.array([[y]])

learning_rate = 0.5

w_1 = np.array([
     [0.5, -0.6],
     [0.1, -0.2],
     [0.1,  0.7]])
W_1 = w_1.T

w_2 = np.array([0.1, -0.3])
W_2 = np.array([w_2]) #Not the transpose because they represent w_1 and w_2 differently

z_1 = np.dot(x,w_1)
Z_1 = np.dot(W_1,X)

f_1 = sigmoid(z_1)
F_1 = sigmoid(Z_1)

z_2 = np.dot(f_1,w_2)
Z_2 = np.dot(W_2,F_1)

f_2 = sigmoid(z_2)
F_2 = sigmoid(Z_2)

error_2 = f_2 - y
Error_2 = F_2 - Y

error_out_2 = error_2 * f_2 * (1 - f_2)
Error_out_2 = Error_2 * F_2 * (1 - F_2)

delta_w_2 = learning_rate * error_out_2 * f_1
Delta_W_2 = learning_rate * np.dot(Error_out_2,F_1.T) 


error_1 = np.dot(error_out_2, w_2)
Error_1 = np.dot(Error_2,F_2 * (1 - F_2) * W_2)

error_out_1 = error_1 * f_1 * (1 - f_1)
Error_out_1 = Error_1.T * F_1 * (1 - F_1)

Delta_w_1 = learning_rate * error_out_1 * x[:, None]
Delta_W_1 = learning_rate * np.dot(Error_out_1,X.T)

print(Delta_w_1)
print(Delta_W_1)


    

#print(Error_1)                   
                    

#print(f_1)


#print(error_1)
#print(Error_1)


#print(delta_w_2)
#print(Delta_W_2)

print('-----------------------------------------')








[[ -1.77005547e-04   5.11178506e-04]
 [ -3.54011093e-05   1.02235701e-04]
 [  7.08022187e-05  -2.04471402e-04]]
[[ -1.77005547e-04  -3.54011093e-05   7.08022187e-05]
 [  5.11178506e-04   1.02235701e-04  -2.04471402e-04]]
-----------------------------------------
